FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir kafka-python==2.0.2 python-dotenv==1.0.0

COPY schemas/ ./schemas/
COPY producer/ ./producer/

CMD ["python", "producer/transaction_producer.py"]
